name: pine_env
channels:
  - dglteam/label/th24_cu121
  - conda-forge
  - defaults
dependencies:
  - dgl=2.4.0.th24.cu121
  - graphviz=2.50.0
  - numpy=1.26.4
  - pip=25.1
  - python=3.10.17
  - pip:
    - adapters==1.1.0
    - gdown==5.2.0
    - huggingface-hub==0.31.2
    - matplotlib==3.8.0
    - networkx==3.1
    - ogb==1.3.6
    - pandas==2.2.3
    - scikit-learn==1.3.0
    - scipy==1.15.3
    - tokenizers==0.21.1
    - torch==2.4.0
    - torch-geometric==2.4.0
    - tqdm==4.65.0
    - ndlib==5.1.1
